### PR TITLE
Kicad files

### PR DESCRIPTION
**Pull request by yusufm**
schematic and pcb complete, ready for review.

### CODE REVIEW

**Comment by JohnDMcMaster** [comment]
"he's got vias in the component pads. in general that's no good, but if he just wants to hand solder it, it's probably OK"

**Comment by JohnDMcMaster** [comment]
" U3 has a 4.5V threshold so it's never going to release reset (it's tied to a 3.3V rail)"

I remember we had some issues before on this but I thought they had been resolved. I'll take another look

**Comment by yusufm** [comment]
> "he's got vias in the component pads. in general that's no good, but if he just wants to hand solder it, it's probably OK"

Since we plan on handsoldering, I'll leave these vias as is, unless you have an objection.

**Comment by yusufm** [comment]
> " U3 has a 4.5V threshold so it's never going to release reset (it's tied to a 3.3V rail)"
> 
> I remember we had some issues before on this but I thought they had been resolved. I'll take another look

ok, take a look and let me know what the resolution is.

**Comment by JohnDMcMaster** [comment]
Cleaned up main page: https://proghq.org/wiki/index.php/BPM_WWAVUSBEPP

I'm in contact with someone that has made a successful adapter. Trying to confirm our pinout is correct

**Comment by JohnDMcMaster** [comment]
I made a few small changes locally. Lets merge in and then I'll send those upstream

**Pull request merged**
